version: "2.2"

services:
  etl-app:
    build: .
    container_name: 'etl-app'
    environment:
      - PGPORT=15432
      - PGHOST=dbglobant
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=myglobantpass
      - PGDATABASE=postgres
      - enviroment=dev
    depends_on:
      - dbglobant
    ports:
      - 80:80
  
  dbglobant:
    image: postgres
    restart: on-failure
    container_name: 'dbglobant'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=myglobantpass
    command: -p 15432
    ports:
      - 15432:15432
    # volumes: 
    #       # copy the sql script to create tables
    #   - ./init_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    # ports:
    #   - 5431:5432
    # expose:
    #   - 5432